version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - ../artefacts/mlflow:/mlflow
  gui:
    build:
      context: ./gui
      dockerfile: gui.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - mynetwork
    volumes:
      - ../artefacts/mlflow:/mlflow
    
volumes:
  mlflow:
    external: true
    name: mlflow

networks:
  mynetwork:
