version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - ../artefacts/mlflow:/app/mlflow
      - ../assets/processed:/app/assets/processed
  gui:
    build:
      context: ./gui
      dockerfile: gui.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - mynetwork
    volumes:
      - ../artefacts/mlflow:/app/mlflow
    
volumes:
  mlflow:

networks:
  mynetwork:
