version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - mlflow:/mlflow
  gui:
    build:
      context: ./gui
      dockerfile: gui.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - mynetwork
    volumes:
      - mlflow:/mlflow
  train:
    build:
      context: ./train
      dockerfile: train.Dockerfile
    networks:
      - mynetwork
    volumes:
      - mlflow:/mlflow
      - ../assets/processed:/data/assets/processed
    environment:
      - MLFLOW_TRACKING_URI=file:/mlflow
    
volumes:
  mlflow:

networks:
  mynetwork:
